// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-variants/DarkGlass.tsx": () => import("../components/mockups/dashboard-variants/DarkGlass.tsx"),
  "./components/mockups/dashboard-variants/EarthyBold.tsx": () => import("../components/mockups/dashboard-variants/EarthyBold.tsx"),
  "./components/mockups/dashboard-variants/GradientFlow.tsx": () => import("../components/mockups/dashboard-variants/GradientFlow.tsx"),
  "./components/mockups/masakhe-loaders/FlagStripes.tsx": () => import("../components/mockups/masakhe-loaders/FlagStripes.tsx"),
  "./components/mockups/masakhe-loaders/OrbitDots.tsx": () => import("../components/mockups/masakhe-loaders/OrbitDots.tsx"),
  "./components/mockups/masakhe-loaders/PulseM.tsx": () => import("../components/mockups/masakhe-loaders/PulseM.tsx"),
  "./components/mockups/nero-sections/CurrentOperations.tsx": () => import("../components/mockups/nero-sections/CurrentOperations.tsx"),
  "./components/mockups/nero-sections/CurrentTransactions.tsx": () => import("../components/mockups/nero-sections/CurrentTransactions.tsx"),
  "./components/mockups/nero-sections/NeroOperations.tsx": () => import("../components/mockups/nero-sections/NeroOperations.tsx"),
  "./components/mockups/nero-sections/NeroTransactions.tsx": () => import("../components/mockups/nero-sections/NeroTransactions.tsx")
};
